language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

sudo: false

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --prefer-source

script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs --standard=psr2 src/ tests/
